name: Publish image to Docker Hub

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input tags version for publish to Docker'
        required: true
        default: latest
        type: string
      run-test:
        description: 'Run test'
        required: true
        default: true
        type: boolean
      run-linter:
        description: 'Run linter'
        required: true
        default: true
        type: boolean

jobs:
  test:
    if: ${{ github.event.inputs.run-test }} == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: prerelease or not
        id: check_tag
        run: |
          if [$TAG == '']
          then
              echo "::set-output name=tag::latest"
          else
              echo "::set-output name=tag::$TAG"
          fi
        env:
          TAG: ${{ github.event.inputs.tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rozikovp/flask-app:${{ steps.check_tag.outputs.tag }}
