name: Publish image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input tags version for publish to Docker'
        required: true
        default: latest
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rozikovp/flask-app:${{ github.event.inputs.tag }}
