name: CI pipe run and build

#.github/workflows/CI_pipe2.yml
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'develop'

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: List of repo
        run: ls ${{ github.workspace }}
      - name: Setup python version 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint
          pip install pytest
      - name: Run linter
        run: echo '1'
      - name: Run test
        run: echo '1'
  build-docker:
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag flask-app:$(date +%s)
