name: CI pipe run and build

on: 
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: ubuntu-18.04
      steps:
          uses: actions/checkout@v3
        - name: List of repo
          run: ls ${{github.workspace}}
        - name: Setup python version 3
          uses: actions/setup-python@v4
          with:
            python-version: '3.7'
        - name: Install dependencies
          run: |
            pip install --no-cache-dir -r requirements.txt
