name: hello-world

# on: push
on:
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches: ['main', 'develop']
  workflow_dispatch:
    inputs:
      tag:
        description: Description
        type: string
        required: true
        default: "AA BB"


jobs:
  hello-job:
    runs-on: ubuntu-20.04
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: echo "💡 The ${{ github.repository }} "
  job-2:
    runs-on: ubuntu-latest
    #needs:
    #  - hello-job
    steps:
      - name: step3
        run: ls
#.github/workflows/hello_world.yml
