name: hello-world

# on: push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hello-job:
    runs-on: ubuntu-20.04
    steps:
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: git log
  job-2:
    runs-on: ubuntu-latest
    needs:
      - hello-job
    steps:
      - name: step3
        run: ls

#.github/workflows/hello_world.yml